### ISSUE TITLE
Possible sensitive data exposure.

### ISSUE THREAD

**Issue by Kuludu** [Coder-Liuu/Tiny-BBS#1]
[https://github.com/Coder-Liuu/Tiny-BBS/blob/a2928cfea6b0af538f274971d8acaf5a49ff9efa/config.py#L6](https://github.com/Coder-Liuu/Tiny-BBS/blob/a2928cfea6b0af538f274971d8acaf5a49ff9efa/config.py#L6)

Possible local environment password exposure here, weak password detected.

**Comment by Coder-Liuu** [comment]
大哥批评的是，是小弟的疏忽！
<img src="https://www.gstatic.com/android/keyboard/emojikitchen/20201001/u1f97a/u1f97a_u1f630.png" style="width:10px" />
